name: test-and-build
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"




      


