name: test-and-build
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7'
    - name: Configure Python environment
      run: |
        pip install pipenv
        pipenv install --dev --ignore-pipfile
    - name: Check types
      run: |
        pipenv run python -m mypy ./tests --config-file ./mypy.ini
        pipenv run python -m mypy ./transformers --config-file ./mypy.ini
    - name: Unit tests
      run: |
        mkdir ./tests/results
        pipenv run python -m pytest --junitxml=./tests/results/results.xml
    





      


